### ISSUE TITLE
Failing link

### ISSUE THREAD

**Issue by brimwats** [jglev/obsidian-apply-patterns-plugin#23]
you link to a CSS script here: "The theme has been enhanced for task management using this CSS snippet. See here for instructions on incorporating CSS snippets in Obsidian."

the link is broken https://gist.github.com/publicus/30f289deb911cc8f8645c946e42f13a6

**Comment by FelipeRearden** [comment]
Hello @brimwats !!!!

I think this link will work :)

https://gist.github.com/jglev/30f289deb911cc8f8645c946e42f13a6

I hope it works :)

Have a great day!

**Comment by jglev** [comment]
@brimwats (and @FelipeRearden), thank you!

This should be fixed in the upcoming [`1.4.0` release](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/1.4.0).

**Comment by jglev** [comment]
Closing now, as I've just now [released `1.4.0`](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/1.4.0).
