### ISSUE TITLE
Apply Patterns no longer appears in the command palette

### ISSUE THREAD

**Issue by swehba** [jglev/obsidian-apply-patterns-plugin#26]
Issue tracker is **ONLY** used for reporting bugs. New feature ideas should be discussed in the [ideas section](https://github.com/publicus/obsidian-apply-patterns-plugin/discussions/categories/ideas). Please use the [Q&A section](https://github.com/publicus/obsidian-apply-patterns-plugin/discussions/categories/q-a) for supporting issues. Please use the search function.

If you encountered the issue after you installed, updated, or reloaded the Apply Patterns plugin, please try restarting obsidian before reporting the bug.

If you want to report a bug, please follow the guide lines below to help me resolve it.

## Expected Behavior
1. Install the Apply Patterns plugin into Obsidian.
2. Within Obsidian, press ⌘P to open the Command Palette.
3. Type "Apply Pattern".
4. You should see a list of the patterns you have defined displayed as something like "Apply Pattern: pattern name".

## Current Behavior
- Instead of seeing any patterns or any commands associated with Apply Patterns, you see nothing.

## Steps to Reproduce
- See Expected Behavior, above.

## Context (Environment)
* Obsidian version: V0.12.19
* Apply Patterns version: 1.3.1
* [ ] I have tried it with all other plugins disabled and the error still occurs

**Comment by swehba** [comment]
P.S. I've been using this very helpful plugin for a long time, and it worked flawlessly until now. Now you cannot even access the command to run it although you can still access the plugin settings and define new regex patterns.

**Comment by jglev** [comment]
@swehba, would you be willing to see whether this issue still presents for you with the new [`1.4.0` pre-release](https://github.com/jglev/obsidian-apply-patterns-plugin/discussions/32)?

I'm going to close this issue for now, but am happy to re-open it with more information!

**Comment by swehba** [comment]
Apply Patterns definitely appears in the Command Palette as of v0.13.19. Thanks for looking into it.

**Comment by seatrout** [comment]
I am getting the same problem with version 1.4.0 and Obsidian 0.13.19 on Windows. I have installed and uninstalled the plugin, stopped and restarted obsidian, multiple times. But I cannot get the plugin to show up either in the list of commands or in the settings panel for plugins, although it shows up as installed in the main list, and clicking on the name there does bring me to this site. So **something** has been installed, but it does not seem to have registered properly with the main program.

**Comment by seatrout** [comment]
Even stranger, when I try this on a different vault, it seems to work. I am going to have to do some more research.

**Comment by jglev** [comment]
@seatrout Please do let me know if you figure out a pattern! I'm not seeing that issue running the same versions in Windows, so I'm definitely curious to learn more!

**Comment by javiavid** [comment]
I have the same problem with empty new vault.
Obsidian 0.13.19
Windows 11

**Comment by jglev** [comment]
@seatrout and @javiavid, thank you both!

I just tried with a completely new vault and _was_ able to replicate the problem. It turns out that there was a bug in the code that checks whether the plugin has just been upgraded. I _think_ that I've fixed it just now, in [version `1.4.1`](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/1.4.1). Please do let me know if this new version addresses the issue.
