### ISSUE TITLE
"Apply pattern to whole document" does not modify file on iPad and iPad

### ISSUE THREAD

**Issue by claremacrae** [jglev/obsidian-apply-patterns-plugin#29]
## Expected Behavior

"Apply pattern to whole document" should apply the pattern to the whole page.

This works for me on Mac, but on iPad it does not change the file - I am confident that the pattern is correct, as when I "select all" and then apply the same pattern, the page does get changed.

On the iPad with a keyboard, the workaround is easy, to `Cmnd+A` and then run the pattern on the selection.

However, on an iPhone, selecting all first is fiddly, as Obsidian does not always pop up the iPhone context menu

## Current Behavior

"Apply pattern to whole document" does not apply the pattern to the whole page on iPad and iPhone, but does on Mac.

## Steps to Reproduce

1. Set up this pattern:

```json
    {
      "name": "TEST - DO NOT USE",
      "done": false,
      "rules": [
        {
          "from": "GitHub",
          "to": "ZZZZZZ",
          "caseInsensitive": false,
          "global": true,
          "multiline": false,
          "sticky": false,
          "disabled": false
        }
      ],
      "collapsed": false
    }
```

2. Set up a scratch document with this content:

```
- [GitHub - Dmitriy-Shulha/obsidian-css-snippets: Most common appearance solutions for Obsidian now in a single place. Initially collected by Klaas: https://forum.obsidian.md/t/how-to-achieve-css-code-snippets/8474](https://github.com/Dmitriy-Shulha/obsidian-css-snippets)  
- [GitHub - UserName/sample-repo-name: Sample:,_()- Description](https://github.com/UserName/sample-repo-name)  
- [GitHub - arnemertz/commandline-videostore-cpp: C++ port of https://github.com/rickjanda/commandline-videostore](https://github.com/arnemertz/commandline-videostore-cpp)  
- [GitHub - chubin/cheat.sh: the only cheat sheet you need](https://github.com/chubin/cheat.sh)  
- [GitHub - copperspice/doxypress](https://github.com/copperspice/doxypress)  
```

3. On iPad, open the above document in Edit mode
4. Open Command Palette
5. Select "Apply Patterns: Apply pattern to **whole document**"
6. Choose the "TEST - DO NOT USE" PATTERN
7. Note that **none** of the GitHub words change to ZZZZZZ

### Steps to confirm that pattern works - via "Select All" on iPad:

1. On iPad, open the above document in Edit mode
2. Select All
3. Open Command Palette
5. Select "Apply Patterns: Apply pattern to **selection**"
6. Choose the "TEST - DO NOT USE" PATTERN
7. Note that **all** of the GitHub words change to ZZZZZZ

### Steps to confirm that pattern works - via "whole document" on Mac:

1. On Mac, open the above document in Edit mode (and have the above pattern set up too)
4. Open Command Palette
5. Select "Apply Patterns: Apply pattern to **whole document**"
6. Choose the "TEST - DO NOT USE" PATTERN
7. Note that **all** of the GitHub words change to ZZZZZZ

So by a process of elimination, it looks like the problem is specific to the iPad and "whole document".

## Context (Environment)
* Obsidian version:
    * iPad and iPhone: 1.0.4 (AppStore version)
    * Mac: 0.12.19
* Apply Patterns version: 1.3.1
* [x] I have tried it with all other plugins disabled and the error still occurs

## Possible Solution

Sorry - no idea.

**Comment by claremacrae** [comment]
I've just updated to the new Obsidian Insider Preview, with Live Preview - and the bug occurs there too.

I think it's using CodeMirror 6, like on mobile - so I speculate that it is likely to be the cause of the error...

**Comment by jglev** [comment]
@claremacrae, thank you for writing this up, and for the update! I really appreciate your detailed report!

I haven't had much time in the last few weeks to debug, but just to confirm, this is on my mind!

**Comment by claremacrae** [comment]
> @claremacrae, thank you for writing this up, and for the update! I really appreciate your detailed report!
> 
> I haven't had much time in the last few weeks to debug, but just to confirm, this is on my mind!

Hi @jglev Many thanks for the reply.

I'm OK for now, as I have a workaround (of selecting the whole document)... If I find myself doing this a lot, I might even create a macro that:

1. selects all and then 
2. applies the pattern

**Comment by jglev** [comment]
@claremacrae, if you're willing and able, would you be open to seeing whether this issue still presents itself for you in the [draft `1.4.0` release](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/1.4.0)? I would be grateful for any additional info; thank you!

**Comment by claremacrae** [comment]
@jglev Many thanks...

I downloaded the 3 files from the 1.4.0 release and copied them over the 1.3.1 files I had previously. And I restarted Obsidian.

Unfortunately the bug is still present.

I note that the manifest file says the new version is 1.3.2 though... So is it

**Comment by claremacrae** [comment]
Screenshot showing diffs in PyCharm:

![image](https://user-images.githubusercontent.com/4840096/147573077-baf34312-0571-4e1c-9f33-e1d9e987c27a.png)

**Comment by claremacrae** [comment]
Apply the pattern to the selected text also no longer works...

This is all on Mac

**Comment by claremacrae** [comment]
Wait - I think I forgot to select the text....

When I select all and apply the selection, I am pretty sure that one time it emptied the whole document - and when I reverted the edit and repeated it, the content didn't change.

**Comment by claremacrae** [comment]
I've reverted back to the previous release for now...

**Comment by claremacrae** [comment]
Here is my settings file, renamed to allow it to be uploaded...
The pattern I am testing with is `"Format GithHub Repo Link"`
[data-json.txt](https://github.com/jglev/obsidian-apply-patterns-plugin/files/7784989/data-json.txt)

**Comment by claremacrae** [comment]
Here is my input file:
[Scratchpad Before.md](https://github.com/jglev/obsidian-apply-patterns-plugin/files/7784995/Scratchpad.Before.md)

**Comment by claremacrae** [comment]
And here is my expected output file:
[Scratchpad After.md](https://github.com/jglev/obsidian-apply-patterns-plugin/files/7784997/Scratchpad.After.md)

(The difference in the H1 text is because of the [obsidian-filename-heading-sync](https://github.com/dvcrn/obsidian-filename-heading-sync) plugin.)

**Comment by claremacrae** [comment]
> I've reverted back to the previous release for now...

I had the problem with the content being deleted again, so restarted Obsidian, having reverted the plugin's content, to get back the old behaviour fully....

**Comment by claremacrae** [comment]
@jglev Hallo - I just wanted to make sure you've seen the comments above, as I forgot to @ you...

**Comment by jglev** [comment]
@claremacrae, thank you very much for all of the above! Seeing your example files were very helpful -- they helped me see and (hopefully) address several issues with the codebase, including that, as you suspected, the plugin was behaving differently for CodeMirror 5 than CodeMirror 6 with Live Preview.

At least on Desktop and Android, your test pattern on your example input text is now working for me in all three modes (Whole Document, Selection, and Whole Lines). Would you be willing to take a look again on iOS? I've updated the files on the [`1.4.0` Release page](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/1.4.0) just now.

**Comment by claremacrae** [comment]
Thank you very much @jglev. I should be able to test this later today.

**Comment by claremacrae** [comment]
> At least on Desktop and Android, your test pattern on your example input text is now working for me in all three modes (Whole Document, Selection, and Whole Lines). Would you be willing to take a look again on iOS? I've updated the files on the [`1.4.0` Release page](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/1.4.0) just now.

That's actually quite scary to me that you can update files attached to a release.

The tag associated with the release has not changed, and it implies that the release is several days old.

But the contents of the release are different, you say...

It tells me that I can no longer rely on assets in a release reproducibly matching the version listed in the release itself. 😱

**Comment by claremacrae** [comment]
Could you please let know what source-code commit ID matches the version of files currently in the 1.4.0 release?

**Comment by claremacrae** [comment]
Yes, it works - I cannot fool it!

I tried with:

- the legacy editor
- the new editor, in live preview
- the new editor, in source mode

I tried it with partial lines selected, and whole lines, and various other combinations.

It all worked well - thank you very much indeed!

Please can I request that the current 1.4.0 test release is deleted, and a new release is created so that the contents of the release will match the tag in the release?

**Comment by jglev** [comment]
> The tag associated with the release has not changed, and it implies that the release is several days old.

Noted! In the future, I think that I'll explicitly make "beta" tags for pre-releases (e.g., `1.4.0-beta`). This is my first time experimenting with pre-releases in GitHub. Thank you for the feedback!

> Please can I request that the current 1.4.0 test release is deleted, and a new release is created so that the contents of the release will match the tag in the release?

I take your point, and have taken your advice -- I've created [a new `1.4.0` release](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/1.4.0) just now.

**Comment by claremacrae** [comment]
Thanks very much indeed for creating the new release...

Yes, having something like x.y.z-beta1, x.y.z-beta2 or similar is a great idea.

There are times when it's really useful to be able to go back and test earlier versions, so I might even hang on to the beta releases over time, unless one of them turned out to be really broken.

Disclaimer: I am not very experienced with GitHub beta/test releases....
