### ISSUE TITLE
Inconsistent minAppVersion

### ISSUE THREAD

**Issue by claremacrae** [jglev/obsidian-apply-patterns-plugin#34]
A small thing: looking at [this commit](https://github.com/jglev/obsidian-apply-patterns-plugin/commit/e5494130f06be1e25c590397bd53d00806f58a4d) I noticed the minimum app versions were inconsistent...

![image](https://user-images.githubusercontent.com/4840096/147579831-9dc8c957-3b55-4b4e-8e0f-db14513090f0.png)

**Comment by jglev** [comment]
Thank you, @claremacrae!

This should now be fixed, in the [new `1.4.0` release](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/1.4.0).
