### ISSUE TITLE
Does not work with live preview enabled

### ISSUE THREAD

**Issue by javiavid** [jglev/obsidian-apply-patterns-plugin#36]
## Expected Behavior
**hello**

## Current Behavior
Nothing

## Steps to Reproduce
With the following text
**hello **

Apply regex (source has a white space at the beginning)
 \*\*\n
**\n

And nothing happens
if I turn off live preview it works correctly.

## Context (Environment)
* Obsidian version: 0.13.19
* Apply Patterns version: 1.3.1
* [x] I have tried it with all other plugins disabled and the error still occurs

**Comment by jglev** [comment]
@javiavid, thank you!

The `1.4.0` release a couple weeks ago included new code to get the plugin working with live preview; would you be willing to upgrade and see whether that addresses the issue?

**Comment by javiavid** [comment]
I have tried version 1.4.1 and it works well. Thanks

**Comment by jglev** [comment]
Thank you for letting me know!
