### ISSUE TITLE
Rename "Multiline off" setting to "Multiline"

### ISSUE THREAD

**Issue by anselmwang** [jglev/obsidian-apply-patterns-plugin#42]
## Expected Behavior
When I turn on current setting "Multiline off", the wording implies that current rule is NOT a multi-line regex.

## Current Behavior
When I turn on current setting "Multiline off", the current rule becomes a multi-line regex.

## Context (Environment)
* Obsidian version: any version
* Apply Patterns version: 2.0.0
* [x] I have tried it with all other plugins disabled and the error still occurs

## Possible Solution
Rename "Multiline off" setting to "Multiline"

**Comment by jglev** [comment]
Thank you for this, @anselmwang! I got confused when I last changed this; I see your point, and will change it back.

**Comment by anselmwang** [comment]
Thanks a lot.

**Comment by jglev** [comment]
This is addressed as of the [`2.1.0` release](https://github.com/jglev/obsidian-apply-patterns-plugin/releases/tag/2.1.0) just now. Again, thank you!
